import { Resend } from 'resend';

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Check for Resend API key
  const resendApiKey = process.env.RESEND_API_KEY;
  if (!resendApiKey) {
    console.error('RESEND_API_KEY not set in environment variables');
    return res.status(500).json({
      error: 'Email service not configured. Please add RESEND_API_KEY to your environment variables in Vercel.'
    });
  }

  const {
    to,
    automationName,
    condition,
    threshold,
    aiResults,
    sources,
    rulesUsed,
    timestamp
  } = req.body;

  if (!to || !automationName || !aiResults) {
    return res.status(400).json({ error: 'Missing required fields: to, automationName, aiResults' });
  }

  try {
    const resend = new Resend(resendApiKey);

    // Format timestamp
    const formattedTime = timestamp ? new Date(timestamp).toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'short'
    }) : new Date().toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'short'
    });

    // Build email content
    const subject = `🚨 Janus Alert: ${automationName}`;

    const textContent = `
JANUS AUTOMATION ALERT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Automation: ${automationName}
Triggered: ${formattedTime}
Condition: "${condition}" ${threshold ? `(Threshold: ${threshold})` : ''}

${sources ? `DATA SOURCES:\n${sources}\n\n` : ''}${rulesUsed ? `RULES APPLIED:\n${rulesUsed}\n\n` : ''}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI ANALYSIS RESULTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${aiResults}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This alert was generated by Janus AI Data Processing Agent.
    `.trim();

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p { margin: 5px 0 0 0; opacity: 0.9; }
    .alert-info { background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 20px 0; }
    .alert-info strong { color: #856404; }
    .metadata { background: #f8f9fa; padding: 15px; border-radius: 4px; margin: 20px 0; font-size: 14px; }
    .metadata div { margin: 5px 0; }
    .results { background: white; border: 1px solid #dee2e6; padding: 20px; border-radius: 4px; margin: 20px 0; }
    .results h2 { margin-top: 0; color: #495057; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
    .results pre { white-space: pre-wrap; word-wrap: break-word; background: #f8f9fa; padding: 15px; border-radius: 4px; overflow-x: auto; }
    .footer { text-align: center; padding: 20px; color: #6c757d; font-size: 12px; border-top: 1px solid #dee2e6; margin-top: 30px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Janus Automation Alert</h1>
    <p>${automationName}</p>
  </div>

  <div class="alert-info">
    <strong>Condition Met:</strong> "${condition}" ${threshold ? `<br><strong>Threshold:</strong> ${threshold}` : ''}
    <br><strong>Triggered:</strong> ${formattedTime}
  </div>

  ${sources || rulesUsed ? `
  <div class="metadata">
    ${sources ? `<div><strong>📊 Data Sources:</strong><br>${sources.replace(/\n/g, '<br>')}</div>` : ''}
    ${rulesUsed ? `<div style="margin-top: 10px;"><strong>📋 Rules Applied:</strong><br>${rulesUsed.replace(/\n/g, '<br>')}</div>` : ''}
  </div>
  ` : ''}

  <div class="results">
    <h2>AI Analysis Results</h2>
    <pre>${aiResults}</pre>
  </div>

  <div class="footer">
    <p>This alert was generated by <strong>Janus AI Data Processing Agent</strong></p>
    <p>To manage your automations, visit your Janus dashboard</p>
  </div>
</body>
</html>
    `.trim();

    console.log('Sending email to:', to);
    const response = await resend.emails.send({
      from: 'Janus Alerts <alerts@resend.dev>', // Will need to update this with your domain
      to: to,
      subject: subject,
      text: textContent,
      html: htmlContent
    });

    console.log('Email sent successfully:', response);
    return res.status(200).json({ success: true, messageId: response.id });

  } catch (err) {
    console.error('Failed to send email:', err);
    return res.status(500).json({
      error: 'Failed to send email: ' + err.message,
      details: err.toString()
    });
  }
}
